# for forcerule.yml

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯"
type = "select"
rule = ["(?i:HK|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|é¦™æ¸¯)"]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡"
type = "select"
rule = ["(SG|ç‹®åŸ|å¡)"]

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ å°æ¹¾"
type = "select"
rule = ["(å°|TW)"]

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬"
type = "select"
rule = ["(JP|Japan|æ—¥æœ¬|æ²ªæ—¥)"]

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½"
type = "select"
rule = ["(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ©å›½|éŸ“)"]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½"
type = "select"
rule = ["(ç¾|ä¸­ç¾|æ²ªç¾|US|çº½çº¦|æ³¢ç‰¹å…°|æ—§é‡‘å±±|åœ£ä½•å¡)"]

[[custom_groups]]
name = "ğŸŒ å…¶ä»–åœ°åŒº"
type = "select"
rule = ["(æ¾³é—¨|å°åº¦|åŠ æ‹¿å¤§|è‹±å›½|æ¾³å¤§|æ‚‰å°¼|è·å…°|è¶Šå—|å¾·å›½|å—é|æ„å¤§åˆ©|è¥¿ç­ç‰™|åŒˆç‰™åˆ©|æ³°å›½|é©¬æ¥è¥¿äºš|ä»¥è‰²åˆ—|æ·å…‹)"]

[[custom_groups]]
name = "ğŸ›’ ä½ä»·è´­ç‰©"
type = "select"
rule = ["(é˜¿æ ¹å»·|åœŸè€³å…¶|RU|ä¿„ç½—æ–¯|è²å¾‹å®¾|å·´è¥¿|è´­ç‰©)"]


