# å±€åŸŸç½‘
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

# Unbreak
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Advertising.list"

[[rulesets]]
group = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list"

# è‡ªå®šä¹‰ç›´è¿
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "../rules/custom_rules.list"
type = "clash-domain"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OneDrive.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Game/Steam.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Riot/Riot.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"

[[rulesets]]
group = "ğŸ¥ NETFLIX"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Video/Netflix.list"

[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Video/YouTube.list"

[[rulesets]]
group = "ğŸŒ Hulu"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Video/Hulu.list"

[[rulesets]]
group = "ğŸµ Spotify"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ¹ Twitch"
ruleset = "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitch/Twitch.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ“º æ¸¯å°ç•ªå‰§"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/StreamingSE.list"

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Streaming.list"

[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Telegram/Telegram.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/China.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/ChinaIP.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"


